# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance_gitlab
    image: ${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:20.04}
    pre_build_image: true
    privileged: true
    systemd: always
    tty: true
    override_command: false
lint: |
  yamllint --strict --format colored . &&
  ansible-lint -v --force-color --offline --exclude .pipenv/ . molecule/
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    check: converge.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      instance_gitlab:
        gitlab_edition: "gitlab-ce"
#        gitlab_version: "14.5.2"
#        gitlab_release: "ce.0"
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy

...
